name: CI

on:
   pull_request:

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: ğŸ— Checkout repository
           uses: actions/checkout@v4
           with:
              submodules: true

         - name: ğŸ— Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '24'
              
         - name: ğŸ— Install pnpm
           run: corepack enable && corepack use pnpm

         - name: ğŸ— Install dependencies with pnpm
           run: pnpm run repo:init

         - name: âœ” Check TypeScript types
           run: pnpm run typecheck

         - name: ğŸš§ Lint
           run: pnpm run lint

         - name: ğŸ§ª Run project tests
           run: pnpm run test

         - name: ğŸ— Bundle generators and build Modules
           run: pnpm run build

         - name: ğŸ§ª Run e2e tests
           run: pnpm run e2e

         - name: ğŸ§ª Run examples tests
           run: pnpm run examples
