name: Publish

on: workflow_dispatch

permissions:
   # Give the default GITHUB_TOKEN write permission to commit and push the
   # added or changed files to the repository.
   contents: write

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: ğŸ— Checkout repository
           uses: actions/checkout@v5
           with:
              submodules: true

         - name: ğŸ— Setup Node.js
           uses: actions/setup-node@v5
           with:
              node-version: '24'
              registry-url: 'https://registry.npmjs.org'

         - name: ğŸ— Install pnpm
           run: corepack enable && corepack use pnpm

         - name: ğŸ— Install dependencies with pnpm
           run: pnpm run repo:init

         - name: âš™ï¸ Dump BDS Docs
           run: pnpm run dump:run

         - name: ğŸ— Build images
           run: pnpm run build

         - name: ğŸ— Bundle types
           run: PUBLISH=1 pnpm build:src

         - name: ğŸ— Update versions
           run: pnpm repo:publish

         - uses: stefanzweifel/git-auto-commit-action@v6
           with:
              commit_message: Update package.json versions

         - name: Publish changes
           run: pnpm -r publish
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
